### ISSUE TITLE
Missing non-headless Alpine images

### ISSUE THREAD

**Issue by p-bakker** [adoptium/containers#356]
### Please add the exact image (with tag) that you are using

eclipse-temurin:18.0.2.1_1-jre-alpine

### Please add the version of Docker you are running

N/A

### What happened?

Why are only headless images supported for all Alpine-based images?

I see other Alpine-based images like azul/zulu-openjdk-alpine support both a headless and a headfull version, so it doesn't seem to be a limitation of Java on Alpine

Reason I'm looking for this is that we use eclipse-temurin:18.0.2.1_1-jre-alpine in production, but in our CI pipeline this doesn't work as for some steps we need a headfull Java. And in order to make sure our CI environment is an similar to our production environment, I rather not use a completely different image in the CI environment 

### Relevant log output

```shell
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /opt/java/openjdk/lib/libawt_xawt.so
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
at java.base/java.lang.Runtime.load0(Runtime.java:785)
at java.base/java.lang.System.load(System.java:1979)
at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:322)
at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:289)
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
at java.base/java.lang.System.loadLibrary(System.java:2015)
at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
at java.desktop/java.awt.EventQueue.isDispatchThread(EventQueue.java:1089)
at java.desktop/javax.swing.SwingUtilities.isEventDispatchThread(SwingUtilities.java:1493)
at com.servoy.automation.jsunit.smartclient.ServoyJSUnitTestRunner.suite(ServoyJSUnitTestRunner.java:114)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

**Comment by gdams** [comment]
@p-bakker unfortunately due to technical limitations, we cannot ship a headful Alpine binary. At the time that we made the choice to ship Alpine, we did lots of market research and determined that nearly all Alpine users intentionally chose the lightweight OS for its size and were unlikely to be running a headful app.
