### ISSUE TITLE
[Bug]: Maven in Alpine-Image not working (ClassNotFoundException)

### ISSUE THREAD

**Issue by fabian-froehlich** [adoptium/containers#497]
### Please add the exact image (with tag) that you are using

21.0.2_13-jdk-alpine

### Please add the version of Docker you are running

25.0.2

### What happened?

Switching from `21.0.1_12-jdk-alpine` to `21.0.2_13-jdk-alpine` causes some problems with `maven`. The alpine JDK image is used as a base for building our builder image for gitlab ci/cd.

The minimal example dockerfile looks like this:

```
FROM eclipse-temurin:21.0.1_12-jdk-alpine

# upgrade alpine linux
RUN apk update && apk add --upgrade apk-tools && apk upgrade --available && rm -rf /var/cache/apk/*

# install Build-Helper
RUN apk add --no-cache \
    maven

CMD ["bash"]
```

Executing `mvn -v` results in this error:
```
$ mvn -v
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher
```
The container runs on `gitlab-runner 16.7.0`

Between the two images, the alpine version has been bumped from 3.18 to 3.19. The java version, which is a dependency of `maven`, has also been bumped. So I could imagine a conflict between the oracle open jdk and the temurin jdk. 

### Relevant log output

```shell
#0 building with "default" instance using docker driver
#1 [internal] load build definition from dockerfile_jdk21
#1 transferring dockerfile: 320B done
#1 DONE 0.1s
#2 [internal] load .dockerignore
#2 transferring context: 41B done
#2 DONE 0.1s
#3 [auth] eclipse-temurin:pull token for custom-artifactory.com
#3 DONE 0.0s
#4 [internal] load metadata for custom-artifactory.com/eclipse-temurin:21.0.2_13-jdk-alpine
#4 DONE 1.1s
#5 [1/3] FROM custom-artifactory.com/eclipse-temurin:21.0.2_13-jdk-alpine@sha256:6da40af213861c1b9cc475affa011d395d4dbcf0cb031b6a5d05a658fd9e3c5e
#5 resolve custom-artifactory.com/eclipse-temurin:21.0.2_13-jdk-alpine@sha256:6da40af213861c1b9cc475affa011d395d4dbcf0cb031b6a5d05a658fd9e3c5e 0.0s done
#5 sha256:6da40af213861c1b9cc475affa011d395d4dbcf0cb031b6a5d05a658fd9e3c5e 549B / 549B done
#5 sha256:82698e23d15ada036bc176f6fb210401e0679cd0a4b1e71d05e7329982d6062c 1.37kB / 1.37kB done
#5 sha256:f13b621e73dc63fb6be52dc6540fb34c92b98a0e85c69dea04289c03aa53d91b 4.92kB / 4.92kB done
#5 sha256:4abcf20661432fb2d719aaf90656f55c287f8ca915dc1c92ec14ff61e67fbaf8 1.05MB / 3.41MB 0.1s
#5 sha256:59648cfc069f04a8d0eece9cae80e25155888dc9b5de722b58603efafaa0d78b 2.10MB / 13.14MB 0.1s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 1.05MB / 158.61MB 0.1s
#5 sha256:4abcf20661432fb2d719aaf90656f55c287f8ca915dc1c92ec14ff61e67fbaf8 3.41MB / 3.41MB 0.2s done
#5 sha256:59648cfc069f04a8d0eece9cae80e25155888dc9b5de722b58603efafaa0d78b 5.24MB / 13.14MB 0.2s
#5 extracting sha256:4abcf20661432fb2d719aaf90656f55c287f8ca915dc1c92ec14ff61e67fbaf8 0.1s
#5 sha256:59648cfc069f04a8d0eece9cae80e25155888dc9b5de722b58603efafaa0d78b 7.34MB / 13.14MB 0.3s
#5 sha256:98795b95bb4830f88ab5d81f355f8a6f3bd833705d858023f9b58c42457db454 179B / 179B 0.2s done
#5 sha256:c4451c8b3dbe1616b4f1d08ac6cbd135f48e3d3393f2c37402ac18b0b845dfdc 716B / 716B 0.3s done
#5 sha256:59648cfc069f04a8d0eece9cae80e25155888dc9b5de722b58603efafaa0d78b 10.49MB / 13.14MB 0.5s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 10.49MB / 158.61MB 0.5s
#5 extracting sha256:4abcf20661432fb2d719aaf90656f55c287f8ca915dc1c92ec14ff61e67fbaf8 0.3s done
#5 sha256:59648cfc069f04a8d0eece9cae80e25155888dc9b5de722b58603efafaa0d78b 13.14MB / 13.14MB 0.6s done
#5 extracting sha256:59648cfc069f04a8d0eece9cae80e25155888dc9b5de722b58603efafaa0d78b
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 19.92MB / 158.61MB 0.8s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 28.31MB / 158.61MB 1.3s
#5 extracting sha256:59648cfc069f04a8d0eece9cae80e25155888dc9b5de722b58603efafaa0d78b 0.8s done
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 36.70MB / 158.61MB 1.7s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 47.19MB / 158.61MB 2.2s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 55.57MB / 158.61MB 2.6s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 66.06MB / 158.61MB 3.1s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 77.59MB / 158.61MB 3.5s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 87.03MB / 158.61MB 3.7s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 97.52MB / 158.61MB 4.0s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 111.15MB / 158.61MB 4.4s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 122.68MB / 158.61MB 4.7s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 135.27MB / 158.61MB 5.0s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 144.70MB / 158.61MB 5.2s
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 155.19MB / 158.61MB 5.4s
#5 extracting sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e
#5 sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 158.61MB / 158.61MB 5.6s done
#5 extracting sha256:6b168e20b9f2c7cde9300b36733340d229efb681e7862b716580cdb07cdb572e 4.3s done
#5 extracting sha256:98795b95bb4830f88ab5d81f355f8a6f3bd833705d858023f9b58c42457db454
#5 extracting sha256:98795b95bb4830f88ab5d81f355f8a6f3bd833705d858023f9b58c42457db454 done
#5 extracting sha256:c4451c8b3dbe1616b4f1d08ac6cbd135f48e3d3393f2c37402ac18b0b845dfdc done
#5 DONE 10.4s
#6 [2/3] RUN apk update && apk add --upgrade apk-tools && apk upgrade --available && rm -rf /var/cache/apk/*
#6 0.272 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
#6 0.444 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
#6 0.839 v3.19.1-26-g2c7dab72cd7 [https://dl-cdn.alpinelinux.org/alpine/v3.19/main]
#6 0.839 v3.19.1-28-g2f20f968460 [https://dl-cdn.alpinelinux.org/alpine/v3.19/community]
#6 0.839 OK: 22982 distinct packages available
#6 1.309 OK: 40 MiB in 39 packages
#6 1.744 OK: 40 MiB in 39 packages
#6 DONE 2.1s
#7 [3/3] RUN apk add --no-cache     maven
#7 0.494 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
#7 0.629 fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
#7 1.031 (1/21) Installing java-common (0.5-r0)
#7 1.045 (2/21) Installing java-cacerts (1.0-r1)
#7 1.058 (3/21) Installing openjdk21-jre-headless (21.0.2_p13-r0)
#7 2.385 (4/21) Installing libxau (1.0.11-r3)
#7 2.398 (5/21) Installing libmd (1.1.0-r0)
#7 2.410 (6/21) Installing libbsd (0.11.7-r3)
#7 2.423 (7/21) Installing libxdmcp (1.1.4-r3)
#7 2.436 (8/21) Installing libxcb (1.16-r0)
#7 2.459 (9/21) Installing libx11 (1.8.7-r0)
#7 2.498 (10/21) Installing libxext (1.3.5-r3)
#7 2.511 (11/21) Installing libxi (1.8.1-r2)
#7 2.524 (12/21) Installing libxrender (0.9.11-r4)
#7 2.539 (13/21) Installing libxtst (1.2.4-r4)
#7 2.551 (14/21) Installing alsa-lib (1.2.10-r0)
#7 2.578 (15/21) Installing giflib (5.2.1-r5)
#7 2.591 (16/21) Installing libjpeg-turbo (3.0.1-r0)
#7 2.609 (17/21) Installing lcms2 (2.15-r4)
#7 2.625 (18/21) Installing openjdk21-jre (21.0.2_p13-r0)
#7 2.663 (19/21) Installing openjdk21-jmods (21.0.2_p13-r0)
#7 3.428 (20/21) Installing openjdk21-jdk (21.0.2_p13-r0)
#7 3.520 (21/21) Installing maven (3.9.5-r0)
#7 3.621 Executing busybox-1.36.1-r15.trigger
#7 3.627 Executing ca-certificates-20230506-r0.trigger
#7 3.742 Executing java-common-0.5-r0.trigger
#7 3.749 OK: 341 MiB in 60 packages
#7 DONE 4.2s
```

**Comment by gdams** [comment]
@fabian-froehlich I've run your steps and it appears to me that when you download `maven` inside an Alpine container it downloads the Alpine build of OpenJDK21 rather than using Temurin. I would suggest that the best approach for you would be to switch to the official docker image (`maven:3-eclipse-temurin-21-alpine`)

**Comment by fabian-froehlich** [comment]
@gdams good to see, that there is also an image for that! Sadly the issue remains the same for the Java-21 part.

Java 17
```bash
$ mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /usr/share/maven
Java version: 17.0.10, vendor: Eclipse Adoptium, runtime: /opt/java/openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-169-generic", arch: "amd64", family: "unix"
```

Java 21
```bash
$ mvn -v
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher
```

**Comment by gdams** [comment]
that's strange, I'm not able to reproduce this on aarch64 so I'll try on amd64:

```output
/ # mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /usr/share/maven
Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: /opt/java/openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.4.16-linuxkit", arch: "aarch64", family: "unix"
```

**Comment by gdams** [comment]
I'm also not able to reproduce this on an amd64 box:

```output
/ # mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /usr/share/maven
Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: /opt/java/openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-126-generic", arch: "amd64", family: "unix"
```

**Comment by gdams** [comment]
@fabian-froehlich I wonder if you're experiencing the same error observed in https://stackoverflow.com/questions/11118237/maven-error-could-not-find-or-load-main-class-org-codehaus-plexus-classworlds-l. Can you please check through the solutions here?

**Comment by fabian-froehlich** [comment]
Unfortunately no hint changed anything. I figured out, that when I execute "mvn -v" from within the docker build phase `RUN mvn -v` it works. But it does not in the final Image. Maybe `CMD ["bash"]` is the problem?

Interestingly the debug mode of bash shows the error in ci/cd environment and local as well. This time even for the JDK-17 variant of the image:
```bash
$ echo $M2_HOME
$ echo $M2
$ echo $M3_HOME
$ echo $JAVA_HOME
/opt/java/openjdk
$ echo $PATH
/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ bash -x mvn -v
+ '[' -z '' ']'
+ '[' -f /usr/local/etc/mavenrc ']'
+ '[' -f /etc/mavenrc ']'
+ '[' -f /root/.mavenrc ']'
+ cygwin=false
+ mingw=false
+ case "`uname`" in
++ uname
+ PRG=mvn
+ '[' -h mvn ']'
++ pwd
+ saveddir=/project/path/image
++ dirname mvn
+ MAVEN_HOME=./..
++ cd ./..
++ pwd
+ MAVEN_HOME=/project/path/common
+ cd /project/path/image
+ false
+ false
+ '[' -z /opt/java/openjdk ']'
+ JAVACMD=/opt/java/openjdk/bin/java
+ '[' '!' -x /opt/java/openjdk/bin/java ']'
++ echo '/project/path/common/boot/plexus-classworlds-*.jar'
+ CLASSWORLDS_JAR='/project/path/common/boot/plexus-classworlds-*.jar'
+ CLASSWORLDS_LAUNCHER=org.codehaus.plexus.classworlds.launcher.Launcher
+ false
++ find_maven_basedir -v
+++ find_file_argument_basedir -v
++++ pwd
+++ basedir=/project/path/image
+++ found_file_switch=0
+++ for arg in "$@"
+++ '[' 0 -eq 1 ']'
+++ '[' -v = -f -o -v = --file ']'
+++ echo /project/path/image
++ basedir=/project/path/image
++ wdir=/project/path/image
++ '[' /project/path/image '!=' / ']'
++ '[' -d /project/path/image/.mvn ']'
+++ cd /project/path/image/..
+++ pwd
++ wdir=/project/path/common
++ '[' /project/path/common '!=' / ']'
++ '[' -d /project/path/common/.mvn ']'
+++ cd /project/path/common/..
+++ pwd
++ wdir=/builds/pvog
++ '[' /builds/pvog '!=' / ']'
++ '[' -d /project/path/.mvn ']'
+++ cd /project/path/..
+++ pwd
++ wdir=/builds
++ '[' /builds '!=' / ']'
++ '[' -d /builds/.mvn ']'
+++ cd /builds/..
+++ pwd
++ wdir=/
++ '[' / '!=' / ']'
++ echo /project/path/image
+ MAVEN_PROJECTBASEDIR=/project/path/image
++ concat_lines /project/path/image/.mvn/jvm.config
++ '[' -f /project/path/image/.mvn/jvm.config ']'
+ MAVEN_OPTS=' '
+ false
+ export MAVEN_PROJECTBASEDIR
+ MAVEN_CMD_LINE_ARGS='/root/.m2 -v'
+ export MAVEN_CMD_LINE_ARGS
+ exec /opt/java/openjdk/bin/java -classpath '/project/path/common/boot/plexus-classworlds-*.jar' -Dclassworlds.conf=/project/path/common/bin/m2.conf -Dmaven.home=/project/path/common -Dlibrary.jansi.path=/project/path/common/lib/jansi-native -Dmaven.multiModuleProjectDirectory=/project/path/image org.codehaus.plexus.classworlds.launcher.Launcher -v
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher
```

**Comment by gdams** [comment]
> Unfortunately no hint changed anything. I figured out, that when I execute "mvn -v" from within the docker build phase `RUN mvn -v` it works. But it does not in the final Image. Maybe `CMD ["bash"]` is the problem?
> 
> Interestingly the debug mode of bash shows the error in ci/cd environment and local as well. This time even for the JDK-17 variant of the image:
> 
> ```shell
> $ echo $M2_HOME
> $ echo $M2
> $ echo $M3_HOME
> $ echo $JAVA_HOME
> /opt/java/openjdk
> $ echo $PATH
> /opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> $ bash -x mvn -v
> + '[' -z '' ']'
> + '[' -f /usr/local/etc/mavenrc ']'
> + '[' -f /etc/mavenrc ']'
> + '[' -f /root/.mavenrc ']'
> + cygwin=false
> + mingw=false
> + case "`uname`" in
> ++ uname
> + PRG=mvn
> + '[' -h mvn ']'
> ++ pwd
> + saveddir=/project/path/image
> ++ dirname mvn
> + MAVEN_HOME=./..
> ++ cd ./..
> ++ pwd
> + MAVEN_HOME=/project/path/common
> + cd /project/path/image
> + false
> + false
> + '[' -z /opt/java/openjdk ']'
> + JAVACMD=/opt/java/openjdk/bin/java
> + '[' '!' -x /opt/java/openjdk/bin/java ']'
> ++ echo '/project/path/common/boot/plexus-classworlds-*.jar'
> + CLASSWORLDS_JAR='/project/path/common/boot/plexus-classworlds-*.jar'
> + CLASSWORLDS_LAUNCHER=org.codehaus.plexus.classworlds.launcher.Launcher
> + false
> ++ find_maven_basedir -v
> +++ find_file_argument_basedir -v
> ++++ pwd
> +++ basedir=/project/path/image
> +++ found_file_switch=0
> +++ for arg in "$@"
> +++ '[' 0 -eq 1 ']'
> +++ '[' -v = -f -o -v = --file ']'
> +++ echo /project/path/image
> ++ basedir=/project/path/image
> ++ wdir=/project/path/image
> ++ '[' /project/path/image '!=' / ']'
> ++ '[' -d /project/path/image/.mvn ']'
> +++ cd /project/path/image/..
> +++ pwd
> ++ wdir=/project/path/common
> ++ '[' /project/path/common '!=' / ']'
> ++ '[' -d /project/path/common/.mvn ']'
> +++ cd /project/path/common/..
> +++ pwd
> ++ wdir=/builds/pvog
> ++ '[' /builds/pvog '!=' / ']'
> ++ '[' -d /project/path/.mvn ']'
> +++ cd /project/path/..
> +++ pwd
> ++ wdir=/builds
> ++ '[' /builds '!=' / ']'
> ++ '[' -d /builds/.mvn ']'
> +++ cd /builds/..
> +++ pwd
> ++ wdir=/
> ++ '[' / '!=' / ']'
> ++ echo /project/path/image
> + MAVEN_PROJECTBASEDIR=/project/path/image
> ++ concat_lines /project/path/image/.mvn/jvm.config
> ++ '[' -f /project/path/image/.mvn/jvm.config ']'
> + MAVEN_OPTS=' '
> + false
> + export MAVEN_PROJECTBASEDIR
> + MAVEN_CMD_LINE_ARGS='/root/.m2 -v'
> + export MAVEN_CMD_LINE_ARGS
> + exec /opt/java/openjdk/bin/java -classpath '/project/path/common/boot/plexus-classworlds-*.jar' -Dclassworlds.conf=/project/path/common/bin/m2.conf -Dmaven.home=/project/path/common -Dlibrary.jansi.path=/project/path/common/lib/jansi-native -Dmaven.multiModuleProjectDirectory=/project/path/image org.codehaus.plexus.classworlds.launcher.Launcher -v
> Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher
> Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.classworlds.launcher.Launcher
> ```

Ahh this makes sense, we removed bash from the alpine image to keep it lightweight. You'll need to manually install it or switch to using `sh` as your CMD

**Comment by fabian-froehlich** [comment]
You removed `bash` only from the JDK-21 image, or from the JDK-17 image as well? Is it not strange, that `bash -x mvn -v" does produce some output if there is no bash installed in the first place.

In the first post (at the time I was not using the special maven image)  I was installing `bash` with `apk add`. 
Applying this to `maven:3-eclipse-temurin-21-alpine` did no change. Also using `CMD ["sh"]` instead of bash had no impact on the error message.

**Comment by fabian-froehlich** [comment]
I've got my minimal example working this second. I took a look into the original entrypoint of the maven java image.
This file does some configuration, that might be necessary:

```
/usr/local/bin # cat mvn-entrypoint.sh 
#! /bin/sh -eu

# Copy files from /usr/share/maven/ref into ${MAVEN_CONFIG}
# So the initial ~/.m2 is set with expected content.
# Don't override, as this is just a reference setup

copy_reference_files() {
  local log="$MAVEN_CONFIG/copy_reference_file.log"
  local ref="/usr/share/maven/ref"

  if mkdir -p "${MAVEN_CONFIG}/repository" && touch "${log}" > /dev/null 2>&1 ; then
      cd "${ref}"
      local reflink=""
      if cp --help 2>&1 | grep -q reflink ; then
          reflink="--reflink=auto"
      fi
      if [ -n "$(find "${MAVEN_CONFIG}/repository" -maxdepth 0 -type d -empty 2>/dev/null)" ] ; then
          # destination is empty...
          echo "--- Copying all files to ${MAVEN_CONFIG} at $(date)" >> "${log}"
          cp -rv ${reflink} . "${MAVEN_CONFIG}" >> "${log}"
      else
          # destination is non-empty, copy file-by-file
          echo "--- Copying individual files to ${MAVEN_CONFIG} at $(date)" >> "${log}"
          find . -type f -exec sh -eu -c '
              log="${1}"
              shift
              reflink="${1}"
              shift
              for f in "$@" ; do
                  if [ ! -e "${MAVEN_CONFIG}/${f}" ] || [ -e "${f}.override" ] ; then
                      mkdir -p "${MAVEN_CONFIG}/$(dirname "${f}")"
                      cp -rv ${reflink} "${f}" "${MAVEN_CONFIG}/${f}" >> "${log}"
                  fi
              done
          ' _ "${log}" "${reflink}" {} +
      fi
      echo >> "${log}"
  else
    echo "Can not write to ${log}. Wrong volume permissions? Carrying on ..."
  fi
}

owd="$(pwd)"
copy_reference_files
unset MAVEN_CONFIG

cd "${owd}"
unset owd

exec "$@"
```

```dockerfile
FROM maven:3-eclipse-temurin-21-alpine

RUN apk add --no-cache bash
RUN /usr/local/bin/mvn-entrypoint.sh

CMD ["bash"]
```

I am still not sure, why this issue is only present with the Java-21 variant of this image.

**Comment by fabian-froehlich** [comment]
Update:
I got the minimal example with `maven:3-eclipse-temurin-21-alpine` working by selecting another gitlab-runner environment. So there must be a conflicting configuration at our side. I will reach out to our internal it department. Maybe we find out the conflict in the configuration so I can report it here.

**Comment by fabian-froehlich** [comment]
So the problem is reproducible, but we have not found any difference that explains this behavior. 

I can say that these images work
- maven:3.9.5-eclipse-temurin-17-alpine
- maven:3.9.6-eclipse-temurin-17-alpine
- maven:3.9.5-eclipse-temurin-21-alpine

and this one is not
- maven:3.9.6-eclipse-temurin-21-alpine

The patch version here also hides the fact that the newer image contains the minor version upgrade in alpine linux. We install bash in these images. Running a maven command inside the docker build process `RUN mvn - v` is no problem.

It looks like the best idea would be to let this slide a bit and wait for the next patch versions of jdk + maven + alpine that might fix this problem.

**Comment by fabian-froehlich** [comment]
Today we failed to start our spring-boot application based on the latest image `21.0.2_13-jre-alpine`.
Downgrading to `21.0.1_12-jre-alpine` solved that issue.

```
FROM eclipse-temurin:21.0.2_13-jre-alpine as builder

WORKDIR /home/appuser
ARG JAR_FILE=target/application.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM eclipse-temurin:21.0.2_13-jre-alpine

RUN addgroup -g 1000 appuser && adduser -D -u 1000 -G appuser appuser
WORKDIR /home/appuser

EXPOSE 8080

COPY --from=builder /home/appuser/dependencies/ ./
COPY --from=builder /home/appuser/spring-boot-loader/ ./
COPY --from=builder /home/appuser/snapshot-dependencies/ ./
COPY --from=builder /home/appuser/application/ ./

USER appuser

CMD ["sh", "-c", "exec java org.springframework.boot.loader.launch.JarLauncher"]
```

Exception
```
Picked up JAVA_TOOL_OPTIONS: ...
at org.springframework.boot.loader.net.protocol.jar.JarUrlClassLoader.loadClass(JarUrlClassLoader.java:94)
at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
... 6 more
  
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/context/event/ApplicationStartedEvent
at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
at java.base/java.lang.Class.getDeclaredMethod(Unknown Source)
at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:89)
at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)

Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.event.ApplicationStartedEvent
```

It looks like this problem is no longer Maven related and is a more general problem of interoperability between Java, Alpine and our host system.

Shall I create a new issue for that?

**Comment by karianna** [comment]
I think we can keep this open for the history.
